# Generated by Django 4.2 on 2023-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_area', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('area_verde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_arborizada', models.CharField(max_length=3)),
                ('vegetacao_perturbada', models.CharField(max_length=3)),
                ('vegetacao_conservada', models.CharField(max_length=3)),
                ('fauna_nativa', models.CharField(max_length=3)),
                ('mitigacao_ilhas_de_calor', models.CharField(max_length=3)),
            ],
        ),
    ]
